
#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    natural_scroll = true

    touchpad {
        natural_scroll = true
        scroll_factor = 1.0
    }
}

# https://wiki.hypr.land/Configuring/Variables/#gesture
gestures {
    #workspace_swipe_invert = true
    #workspace_swipe_min_speed_to_force = 30
    #workspace_swipe_cancel_ratio = 0.5
    #workspace_swipe_create_new = true
}

# Custom gestures
gesture = 3, horizontal, workspace
gesture = 3, up, dispatcher, exec, pactl set-sink-volume @DEFAULT_SINK@ +10%
gesture = 3, down, dispatcher, exec, pactl set-sink-volume @DEFAULT_SINK@ -10%
gesture = 3, up, mod: CTRL, dispatcher, exec, brightnessctl set 10%+
gesture = 3, down, mod: CTRL, dispatcher, exec, brightnessctl set 10%-

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
