
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor= eDP-1, 2160x1440@60, 0x0, 1
monitor = DP-1, 3840x2160@60, 2160x-1500, 1 # to the right of the laptop
#monitor = DP-1, 3840x2160@60, 0x-2160, 1 # above laptop

# Auto-assign workspaces to monitors
#workspace = 1,monitor:DP-1
#workspace = 2,monitor:DP-1
#workspace = 3,monitor:DP-1
#workspace = 4,monitor:DP-1
#workspace = 5,monitor:eDP-1
#workspace = 6,monitor:eDP-1  
#workspace = 7,monitor:eDP-1
#workspace = 8,monitor:eDP-1
